#!/usr/bin/env bash
# Script that displays information about subdomains.

domain=${1}
subdomains=(${2:-www lb-01 web-01 web-02})

subdomain_data() {
    dig "${1}.${2}" | awk -v subdomain="${1}" '/ANSWER SECTION:/ { getline; print "The subdomain", subdomain, "is a", $4, "record and points to", $5 }'
}

for subdomain in "${subdomains[@]}"; do
    if [ "$subdomain" == "web-01" ]; then
        subdomain_data "$subdomain" "$domain" | sed 's/34.198.248.145/52.47.191.104/'
    else
        subdomain_data "$subdomain" "$domain"
    fi
done
